version: '3'

services:
#  frontend_dev:
#    build:
#      context: .
#      dockerfile: frontend.Dockerfile
#    ports:
#      - 4321:4321
#
#    volumes:
#      - "./astro_frontend/src:/usr/src/app/src" # Files and dirs has the same permissions as host
#      - "./astro_frontend/public:/usr/src/app/public" # Files and dirs has the same permissions as host
#
#    command: bunx --bun astro dev --host

  server_api_dev:
    build:
      context: .
      dockerfile: serverapi.Dockerfile
    environment:
      FLASK_DEBUG: 1
      FLASK_RUN_PORT: 5000
    volumes:
      - ./pyflask_api/src:/home/app/src
    ports:
      - 5000:5000
    command: python src/app.py